[
  "bbenoist.nix"
  "danklinux.dms-theme"
  "dart-code.dart-code"
  "dart-code.flutter"
  "geequlim.godot-tools"
  "jdinhlife.gruvbox"
  "navernoedenis.gruvbox-material-icons"
  "openai.chatgpt"
  "pkief.material-icon-theme"
]
